### ISSUE TITLE
Meteor 0.7.0.1 - templates not found

### ISSUE THREAD

**Issue by wbashir** [cmather/meteor-handlebars-server#11]
I upgraded to the latest version of meteor and my application is breaking. I traced it down to this package not finding my server side defined templates. I am not sure if its the latest version because i am also failing with 0.6.6.3. Is there a specific place the templates have to be in. I put them in my `/server` directory and they used to be found

**Comment by wbashir** [comment]
Ignore, missing the package in packages file but was in smart.json.

**Comment by cmather** [comment]
@warsamebashir, I just added you as a maintainer of this project if you need to make changes. Just let me know what they are before you push major stuff since I'm using this package as well.
