### ISSUE TITLE
Including partials?

### ISSUE THREAD

**Issue by monbro** [cmather/meteor-handlebars-server#15]
Is it possible to do so? Like `{{> subpage}}` ?
I tried that by creating a subpage.handlebars but it tells me: `(STDERR) Error: The partial subpage could not be found`

**Comment by reywood** [comment]
This is supported like so.

Create file `my_header.handlebars`

``` html
<header>My header</header>
```

Create file `my_footer.handlebars`

``` html
<footer>My footer</footer>
```

Create file `xyz.handlebars`

``` handlebars
{{> header}}
some content: {{foo}}
{{> footer}}
```

Now to render your xyz template:

``` javascript
Handlebars.templates.xyz(
    {
        foo: "bar"
    },
    {
        header: Handlebars.templates.my_header,
        footer: Handlebars.template.my_footer
    }
);
```

**Comment by monbro** [comment]
Awesome, thank you!
