### ISSUE TITLE
Incompatibility with 0.9.0

### ISSUE THREAD

**Issue by ryw** [cmather/meteor-handlebars-server#19]
The package cmather:handlebars-server at 1.2.0 is incompatible with Meteor 0.9.0 or later. 
If a new, compatible version of this package exists, running 'meteor update' should cause you to update.

**Comment by cmather** [comment]
Oops thanks Ry. I'll try to update this afternoon!

**Comment by hartwoolery** [comment]
any ETA on this?  trying to update our server and just waiting on this one package : )  Thanks for the great package!

**Comment by cmather** [comment]
Should be good to go now. v0.2.0.

**Comment by cmather** [comment]
Stay tuned for a better solution coming sometime hopefully soon that just uses Blaze to render on the server :).
