### ISSUE TITLE
Handlebars Template Can't be defined in /client

### ISSUE THREAD

**Issue by wbashir** [cmather/meteor-handlebars-server#2]
Thanks for the plugin. It might be helpful to mention that the handlebars template file has to be accessible by the server and thus can't be defined in the /client directory. I was so used to making all of my templates on the client side and spent too long finding this.

**Comment by gabrielhpugliese** [comment]
Wow thanks for that info. Been struggling with that too.

**Comment by cmather** [comment]
Hey sorry guys.
