### ISSUE TITLE
Package still maintained?

### ISSUE THREAD

**Issue by SachaG** [cmather/meteor-handlebars-server#28]
This package hasn't seen much activity recently, so I was wondering if it was still actively maintained? If not, what's the recommended alternative?

**Comment by cmather** [comment]
It's a pretty simple package so it doesn't get that much activity. Is it
not working for you?

**Comment by SachaG** [comment]
It works, I was just going over Telescope's packages and it seemed weird that this one hadn't been updated in so long. But if it ain't broken, don't fix it I guess :)
