### ISSUE TITLE
Share a .handlebars server template with client ?

### ISSUE THREAD

**Issue by jpsarda** [cmather/meteor-handlebars-server#3]
This is not an issue, but I wish to know if there is a way to share a .handlebars file with the client and integrate it into a client template.

(I'm building an app that will export some of the html pages of the app to a service like dropbox. But the export is made server side, and thus I need to build the html pages server side.)

**Comment by ryw** [comment]
In http://carp.io we do this — we use templates on the client to preview the app that we are going to publish as flat HTML to the cloud. We then symlink the files into /private

```
handlebars = Meteor.require 'handlebars'
appRoot    = fs.realpathSync(process.cwd() + "/../")

...

parseTemplate = (templateName) ->
  source = fs.readFileSync(appRoot + "/server/assets/app/themes/#{app.theme}/#{templateName}.html", 'utf8')
  template = handlebars.compile(source)(app)
  lines = template.split('\n')
  lines.splice(1,lines.length-3).join('\n')
```

Closing issue :)
