### ISSUE TITLE
Upgrade - 0.6.5

### ISSUE THREAD

**Issue by wbashir** [cmather/meteor-handlebars-server#4]
I am not sure if this package no longer works with meteor 0.6.5 but i was expecting a undefined error of sort around the new api.export() requirement for all packages wanting to support the latest version(s). 

I get an error when i try to add packages or run my solution

`.meteor/tools/4010e5731d/tools/packages.js:418:19: 'sourcePath' option must be supplied to addJavaScript. Consider passing inputPath. (compiling handlebars-server-tests.handlebars)`

**Comment by cmather** [comment]
Hi @warsamebashir, Yeah I had to update this package to work with 0.6.5, but I never deployed a new version to Atmosphere. I'll do that now. The latest changes are in the repo though.

**Comment by cmather** [comment]
Done. Just update this package. It should be on version 1.1.0.

**Comment by wbashir** [comment]
Thanks for the prompt reply!
