### ISSUE TITLE
Helpers?

### ISSUE THREAD

**Issue by properapp** [cmather/meteor-handlebars-server#6]
Should helpers work with this? I've tried moving around a separate js file with a handful of helpers from my /client folder, to /lib, to /server, etc. but the only spot that doesn't throw errors is from /client. I imagine this is a limitation of Meteor...but are there any quick fixes for this?

**Comment by tgoorden** [comment]
You've probably found a way around this already, but it seems

```
OriginalHandlebars.registerHelper ...
```

works on the server side!
