### ISSUE TITLE
Meteor 0.6.6.2 Upgrade

### ISSUE THREAD

**Issue by wbashir** [cmather/meteor-handlebars-server#8]
Are you having issues with meteor 0.6.6.2 and this plugin, all of my other packages work except this one ?

**Comment by cmather** [comment]
Haven't upgraded quite yet.

**Comment by wbashir** [comment]
@cmather  thanks, let me know when you do

**Comment by wbashir** [comment]
any word on this, easy to reproduce. Create a new solution using meteor 0.6.6.2 and just `mrt add handlebars-server`

**Comment by wbashir** [comment]
Cleaned up and removed my meteorite directory and re-installed everything.
