### ISSUE TITLE
Support for partials ?

### ISSUE THREAD

**Issue by petrometro** [cmather/meteor-handlebars-server#9]
I was really pleased to find this package... I need to be able to generate pdf invoices in my app and so I need to build the invoice in html on the server and then print to pdf with phantomjs. This is just about the only package around that lets me build html on the server...

But - the package doesn't seem to support handlebars partials... which makes building html invoices is made much more complicated. 

Anyone have any ideas on how to implement this ? I've tried all the obvious stuff like
OriginalHandlebars.registerPartial but the partial is never available when I compile the parent template...

**Comment by davedx** [comment]
Did you figure this one out?

**Comment by ryw** [comment]
I merged in https://github.com/EventedMind/meteor-handlebars-server/pull/10 which claims to support partials. I haven't tested, however.

**Comment by davedx** [comment]
It doesn't seem to work for me: Handlebars is throwing that the partial could not be found. Pretty sure I'm using exactly the same code sample as in the PR. Still trying...

**Comment by davedx** [comment]
Aha, it's because the PR is only in the Github repo, not yet in atmosphere.

It does work correctly. Could you push it to atmosphere please so I can deploy it properly?

Thanks!
